# -*- coding: utf-8 -*-
"""square.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RFqn397pvc8ecJMsh-L8c5V_vN_VVUlK
"""

n=5
print(n*n)